create table IF NOT EXISTS USER(
	ID_USER tinyint NOT NULL AUTO_INCREMENT,
	USER_LOGIN varchar(20) NOT NULL,
	USER_PASS varchar(255) NOT NULL,
	PRIMARY KEY(ID_USER)
)ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_spanish2_ci AUTO_INCREMENT=1;

create table IF NOT EXISTS USER_MULTIPLE(
	ID_USER tinyint NOT NULL,
	USER_SESSIONS tinyint NOT NULL DEFAULT 0,
	USER_SESSION_KEY varchar(255) NOT NULL,
	PRIMARY KEY(ID_USER),
	FOREIGN KEY(ID_USER) REFERENCES USER(ID_USER)
)ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_spanish2_ci;


create table IF NOT EXISTS USER_MULTIPLE_ACCESS_1(
	ID_SESSION tinyint NOT NULL,
	USER_KEY  varchar(255) NOT NULL,
	/*
	USER_DATE_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	USER_DATE_CURRENT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	USER_DATE_TEMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	USER_IP varchar(20) NOT NULL,
	USER_BROWSER varchar(255) NOT NULL,
	*/
	USER_TEMP tinyint(1) NOT NULL DEFAULT 1,
	USER_STATUS tinyint(1) NOT NULL DEFAULT 1,
	UNIQUE (ID_SESSION)
)ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_spanish2_ci;

