/*STATIC*/
create table IF NOT EXISTS USER(
	ID_USER tinyint NOT NULL AUTO_INCREMENT,
	USER_LOGIN_NAME varchar(20) NOT NULL,
	USER_LOGIN_PASS varchar(255) NOT NULL,
	USER_STATUS tinyint(1) NOT NULL DEFAULT 1,
	PRIMARY KEY(ID_USER)
)ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_spanish2_ci AUTO_INCREMENT=1;

/*STATIC*/
create table IF NOT EXISTS USER_MULTIPLE(
	ID_USER tinyint NOT NULL,
	USER_SESSIONS tinyint NOT NULL DEFAULT 0,
	USER_SESSION_KEY varchar(255) NOT NULL,
	USER_MULTIPLE_ACCESS varchar(100) NOT NULL,
	PRIMARY KEY(ID_USER),
	FOREIGN KEY(ID_USER) REFERENCES USER(ID_USER)
)ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_spanish2_ci;

/*DYNAMIC*/
create table IF NOT EXISTS USER_MULTIPLE_ACCESS_X(
	ID_SESSION tinyint NOT NULL,
	USER_KEY  varchar(255) NOT NULL,
	USER_DATE_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	USER_DATE_CURRENT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	USER_DATE_TEMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	USER_IP varchar(40) NOT NULL,
	USER_BROWSER varchar(255) NOT NULL,
	USER_TEMP tinyint(1) NOT NULL DEFAULT 1,
	UNIQUE (ID_SESSION)
)ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_spanish2_ci;

/*STATIC*/
create table IF NOT EXISTS DEPARTMENT(
	ID_DEPARTMENT tinyint NOT NULL,
	DEPARTMENT_NAME varchar(255) NOT NULL,
	PRIMARY KEY(ID_DEPARTMENT)
)ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_spanish2_ci;

/*STATIC*/
create table IF NOT EXISTS DEPARTMENT_MULTIPLE(
	ID_DEPARTMENT tinyint NOT NULL,
	DEPARTMENT_STATUS tinyint(1) NOT NULL DEFAULT 1,
	DEPARTMENT_MULTIPLE varchar(100) NOT NULL,
	PRIMARY KEY(ID_DEPARTMENT),
	FOREIGN KEY(ID_DEPARTMENT) REFERENCES DEPARTMENT(ID_DEPARTMENT)
)ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_spanish2_ci;

/*DYNAMIC*/
create table IF NOT EXISTS DEPARTMENT_X(
	ID_USER tinyint NOT NULL,
	PRIVILEGES_READ tinyint(1) NOT NULL DEFAULT 1,
	PRIVILEGES_UPDATE tinyint(1) NOT NULL DEFAULT 1,
	PRIVILEGES_DELETE tinyint(1) NOT NULL DEFAULT 1,
	PRIVILEGES_CREATE tinyint(1) NOT NULL DEFAULT 1,
	ID_STATUS tinyint(1) NOT NULL DEFAULT 1,
	DEPARTMENT_MODULE varchar(100) NOT NULL,
	PRIMARY KEY(ID_USER),
	FOREIGN KEY(ID_USER) REFERENCES USER(ID_USER)
)ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_spanish2_ci;

create table IF NOT EXISTS PRIVILEGES(
	ID_PRIVILEGES tinyint NOT NULL,
	PRIVILEGES_NAME varchar(255) NOT NULL
)ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_spanish2_ci;

create table IF NOT EXISTS PRIVILEGES(
	ID_PRIVILEGES tinyint NOT NULL,
	PRIVILEGES_READ varchar(255) NOT NULL
)ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_spanish2_ci;

